TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += devvgauge.db
DB_INSTALLS += $(TOP)/vgaugeSup/devvgauge.proto

#=======================================
include $(TOP)/configure/RULES
